[package]
name = "doctor-registry-private"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
soroban-sdk = "22.0.0"

[dev-dependencies]
soroban-sdk = { version = "22.0.0", features = ["testutils"] }

[features]
testutils = ["soroban-sdk/testutils"]
